[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/shelf"
  to = "/index.html"
  status = 200